FROM alpine
RUN apk add --no-cache util-linux nodejs nodejs-npm autoconf automake libtool nasm alpine-sdk 
LABEL application=customer-portal

# Copy npm spec and install
WORKDIR /app
COPY package*.json /app/
RUN npm install

# Copy source
COPY . /app

# Run build
ENV GATSBY_TELEMETRY_DISABLED=1
ARG BIGCOMMERCE_BASE_API
ARG BIGCOMMERCE_CLIENT_ID
ARG BIGCOMMERCE_STORE_HASH
ARG BIGCOMMERCE_TOKEN
ARG CONTENTFUL_ACCESS_TOKEN
ARG CONTENTFUL_MANAGEMENT_TOKEN
ARG CONTENTFUL_PREVIEW_TOKEN
ARG CONTENTFUL_SPACE_ID
ARG DATA_DOG_KEY
ARG GATSBY_APPSYNC_URL
ARG GATSBY_AWS_REGION
ARG GATSBY_BIGCOMMERCE_ENDPOINT
ARG GATSBY_COGNITO_POOL_CLIENT_ID
ARG GATSBY_COGNITO_USER_POOL_ID
ARG GATSBY_OAUTH_DOMAIN
ARG GATSBY_OAUTH_REDIRECT_SIGN_IN
ARG GATSBY_OAUTH_REDIRECT_SIGN_OUT
ARG GATSBY_STRIPE_PUBLIC_KEY
ARG GOOGLE_TAG_MANAGER_ID
ARG GATSBY_HUBSPOT_ACCOUNT
ARG GATSBY_HUBSPOT_SEARCHADS_FORMID
ARG GATSBY_HUBSPOT_CANCELYOL_FORMID
ARG GATSBY_PLATFORM_API_KEY
ARG SEGMENT_KEY
ARG SITE_URL
ARG CYPRESS_BASE_URL
ARG CYPRESS_TEST_USER
ARG CYPRESS_TEST_PASSWORD

RUN npm run build
CMD ["npm", "run", "test"]