manage_plan_link_LHS                                            = "(//a[contains(text(),'Manage Plan')])[2]"
manage_plan_welcome_msg                                         = "(//div[3]/div/div/div/button)[1]"
manage_plan_page_yournewplan                                    = "//h2[contains(text(),'Your new plan')]"
manage_plan_trading_name                                        = "//div[4]/div[2]/div/div[2]/div/div[1]/p"
manage_plan_business_address                                    = "//div[4]/div[2]/div/div[2]/div/div[2]/p"
manage_plan_page_profile_option                                 = "//select[@id='profile']"
manage_plan_page_profile_option_premium                         = "//option[contains(text(),'$20.00 - Premium')]"
manage_plan_page_boost_option                                   = "(//select[@id='boost'])[1]"
manage_plan_page_profile_option_bronze                          = "//option[contains(text(),'$30.00 - Bronze')]"
manage_plan_cc_save                                             = "//button[contains(text(),'Save')]"
manage_plan_page_total_banner                                   = "//div[4]/div[2]/div/div[6]"
manage_plan_page_premium_total_amount                           = "//div[4]/div[2]/div/div[6]/div[1]/div[1]/p[1]/strong"
manage_plan_page_staff_total_banner                             = "//div[5]/div[2]/div/div[6]"
manage_plan_page_staff_premium_total_amount                     = "//div[5]/div[2]/div/div[6]/div[1]/div[1]/p[1]/strong"
manage_plan_page_premium_total_amount_value                     = "$20.00 + GST"
manage_plan_page_total_banner_text                              = "//div[4]/div[2]/div/div[6]/div[1]/div[2]"
manage_plan_page_staff_total_banner_text                        = "//div[5]/div[2]/div/div[6]/div[1]/div[2]"
manage_plan_submit_button                                       = "//button[contains(text(),'Submit')]"
manage_plan_submit_success_notification                         = "//div[@class='notification-container']"
manage_plan_page_thankyou                                       = "//h2[contains(text(),'Thank you')]"
manage_plan_thankyoubanner_upgrade_effective_date               = "//div[4]/div[2]/div/div[1]/div/div/p"
manage_plan_thankyoubanner_staff_upgrade_effective_date         = "//div[5]/div[2]/div/div[1]/div/div/p"
manage_profile_view_profile_button                              = "//a[contains(text(),'View your profile')]"
manage_plan_page_profile_option_basic                           = "//option[contains(text(),'$0.00 - Basic')]"
manage_plan_upgrade_amount                                      = "//div[4]/div[2]/div/div[2]/div/div[3]/p/strong"
manage_plan_staff_upgrade_amount                                = "//div[5]/div[2]/div/div[2]/div/div[3]/p/strong"
manage_plan_specific_staff_select_company                       = "//section//form/div[2]/div[2]/div/div[contains(text(),'Test NW Yellow Business 1060153133')]"
manage_plan_profile_option_noboost                              = "//option[contains(text(),'$0.00 - No Boost')]"

