# Customer Portal
portal_my_products_link                                             = "/my-yellow/my-products"
portal_manage_reviews_button                                        = "xpath=//a[contains(text(),'Manage Reviews')]"
business_name_label                                                 = "Ambula - Authentic Sri Lankan Cuisine"
business_name_link_text                                             = "Ambula Takeaway"
business_listing_status_label                                       = "ACTIVE"
business_listing_address_label                                      = "59 Queens Road, Auckland, Auckland"
business_owner_email_id                                             = "kumindu777+ambula@gmail.com"

# Manage Reviews page----------------------------------------------------------------------------------------------
reviews_welcome_modal_close_icon                                    = "xpath=//button[@type='button']/img[@alt='close']"
portal_reply_button                                                 = "xpath=//button[contains(@class,'sc-1ahsdlf-0 eUwybD')]"
sample_review_text                                                  = "Had a great experience with authentic Sri Lankan food. The food, service, and overall value was great! Best wishes on a prosperous future."
portal_response_text_area                                           = "xpath=//*[@id='review-reply']"
sample_response_text                                                = "Thanks for your amazing reviews."
portal_response_submit_button                                       = "xpath=//div[contains(text(),'Submit')]"
portal_response_from_the_owner_label                                = "xpath=//div[contains(text(),'Response from the owner')]"
portal_pending_approval_label                                       = "xpath=//div[contains(text(),'Pending Approval')]"
portal_manage_reviews_title_text                                    = "Ratings & Reviews"
portal_manage_reviews_title_label                                   = "xpath=//div[contains(@class,'sc-bdnylx jPNZAa')]"

# Reviews & Response Admin site------------------------------------------------------------------------------------
reviews_admin_panel_url                                             = "https://services.yellow.co.nz/login/"
reviews_admin_panel_username_textbox                                = "xpath=//input[contains(@class,'ynumber')]"
reviews_admin_panel_password_textbox                                = "xpath=//input[contains(@class,'password')]"
reviews_admin_panel_login_button                                    = "xpath=//input[contains(@class,'btn btn-large btn-primary')]"
reviews_admin_panel_response_link                                   = "xpath=//a[contains(@href,'/review/response')]"
reviews_admin_panel_response_title_label                            = "css=div.title_section.hero-unit.hero-unit-padding-small > h2"
reviews_admin_panel_response_record                                 = "css=div.title_section.hero-unit.hero-unit-padding-small > table > tbody > tr > td:nth-child(2)"
reviews_admin_panel_response_detailed_record                        = "xpath=//a[contains(@href,'https://yellow.co.nz/y/ambula-authentic-sri#reviews_tab')]"
reviews_admin_panel_response_initial_accept_btn                     = "xpath=//a[contains(@class,'btn btn-success')]"
reviews_admin_panel_response_moderate_title_label                   = "css=div.title_section.hero-unit.hero-unit-padding-small > div:nth-child(1) > h2 > a"
reviews_admin_panel_response_moderate_response_button               = "xpath=//a[contains(@class,'btn btn-success')]"
reviews_admin_panel_response_moderate_accept_button                 = "xpath=//button[contains(@class,'btn btn-large btn-success')]"
reviews_admin_panel_channel_dropdown                                = "xpath=//*[@id='channel']"
reviews_admin_panel_response_initial_moderation_button              = "xpath=//a[contains(@href,'/review/response/411561/')]"

# yellow site------------------------------------------------------------------------------------------------------
yellow_business_listing_url                                         = "https://yellow.co.nz/y/ambula-authentic-sri?src=Other&c=302"
yellow_reviews_ratings_label                                        = "xpath=//*[@id='reviewsContainerSidebar']/div/h4"
yellow_reviews_ratings_label_text                                   = "Reviews and ratings"
yellow_review_text_label                                            = "xpath=//div[contains(@class,'review-text')]"
yellow_review_response_title_label                                  = "xpath=//h5[contains(@class,'review-business-response-title')]"
yellow_review_response_title_label_text                             = "Response from Ambula - Authentic Sri Lankan Cuisine:"
yellow_review_response_actual_text_label                            = "xpath=//div[contains(@class,'review-business-response-text')]"

# Response Command Centre site-------------------------------------------------------------------------------------
command_centre_response_url                                         = "https://services.yellow.co.nz/command-centre/review/response/"
reviews_command_centre_username_textbox                             = "xpath=//*[@id='id_username']"
reviews_command_centre_password_textbox                             = "xpath=//*[@id='id_password']"
reviews_command_centre_login_button                                 = "xpath=//*[@id='login-form']/div[3]/input"
reviews_command_centre_response_link                                = "xpath=//*[@id='result_list']/tbody/tr[1]/th/a"
reviews_command_centre_response_text                                = "Review 411561 for 800002172"
reviews_command_centre_response_status_dropdown                     = "xpath=//*[@id='id_status']"
reviews_command_centre_response_delete_button                       = "xpath=//*[@id='response_form']/div/div/p/a"
reviews_command_centre_response_delete_confirm_button               = "xpath=//*[@id='content']/form/div/input[2]"
reviews_command_centre_response_search_textbox                      = "xpath=//*[@id='searchbar']"
reviews_command_centre_response_delete_confirmation_text            = "The response \"Review 411561 for 800002172\" was deleted successfully."

# Gmail
response_approved_email_topic_label                                 = "Your response has been approved"
response_approved_email_body_label                                  = "Thanks for taking the time to respond to the review for your business on Yellow. It is a great way to engage with your customers."