# -----------------------------------------------------------------------------
# My Products Page
# -----------------------------------------------------------------------------
my_products_link_LHS                                                = "(//a[contains(text(),'My products')])[2]"
my_products_registered_user_premium_profile_manageprofile           = "//a[contains(@href,'8ba9fc12-aa1b-5bec-9bc7-911f315dc379')][contains(text(),'Manage Profile')]"
my_products_registered_user_basic_profile_manageprofile             = "//a[contains(@href,'4aa26ee0-6ae3-58c0-a029-125ceb7ea183')][contains(text(),'Manage Profile')]"
# -----------------------------------------------------------------------------
# Contact Information Section
# -----------------------------------------------------------------------------
manage_profile_edit_your_profile_info_title                         = "//h2[contains(text(),'Edit your profile info')]"
manage_profile_business_addlogo_img                                 = "xpath=//img[contains(@alt,'Click here to add a logo')]"
manage_profile_business_logo_img                                    = "xpath=//h2[contains(text(),'Edit your profile info')]/parent::section/section/div/img"
manage_profile_business_logo_img                                    = "xpath=//h2[contains(text(),'Edit your profile info')]/parent::section/section/div/img"
manage_profile_logo_browsefiles                                     = "//button[contains(text(),'Browse files')]"
manage_profile_business_logo_change_button                          = "//reach-portal//button[contains(text(),'Change')]"
manage_profile_business_logo1                                       = "Plumbers1.jpg"
manage_profile_business_logo2                                       = "Plumbers2.jpg"
manage_profile_logo_input                                           = "//input[@type='file']"
manage_profile_business_logo_remove_button                          = "//reach-portal//button[contains(text(),'Remove')]"
manage_profile_edit_save_button                                     = "//reach-portal//button[contains(text(),'save')]"
manage_profile_tradingname_title                                    = "//h5[contains(text(),'Trading name')]"
# manage_profile_tradingname_edit_link                                = "xpath=//section[@class='zk9a6o-0 jEaRPI']/section/ul/li[1]//button"
manage_profile_tradingname_edit_link                                = "xpath=//section[@class='sc-11fpou4-0 cPrOOe']/section/ul/li[1]//button"
manage_profile_tradingname_input                                    = "//input[contains(@placeholder,'Trading name')]"
manage_profile_legalbusinessname_title                              = "//h5[contains(text(),'Legal business name')]"
manage_profile_legalbusinessname_withcrown_title                    = "//h5[contains(text(),'Legal business name')]/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
manage_profile_legalbusinessname_edit_link                          = "xpath=//section[@class='sc-11fpou4-0 cPrOOe']/section/ul/li[2]//button"
manage_profile_legaltradingname_input                               = "//input[contains(@placeholder,'Legal name')]"
manage_profile_physicallocation_title                               = "//h5[contains(text(),'Physical location')]"
manage_profile_physicallocation_edit_link                           = "//h5[contains(text(),'Physical location')]//parent::div/div/button"
manage_profile_physicaladdress_show_title                           = "//h5[contains(text(),'Show your physical location?')]"
manage_profile_current_physical_location                            = "//h5[contains(text(),'Physical location')]//parent::div//parent::li/div[2]"
manage_profile_search_new_address                                   = "(//h2[contains(text(),'Physical location')]//parent::div//button)[1]"
manage_profile_input_new_address                                    = "//span[contains(text(),'Search for your address *')]//parent::div/input"
manage_profile_select_new_address                                   = "//div[@class='pac-item'][1]/span"
manage_profile_physical_address_save                                = "(//h2[contains(text(),'Physical location')]//parent::div//button)[2]"
manage_profile_physicaladdress_show_radiobutton                     = "xpath=//section[@class='zk9a6o-0 jEaRPI']/ul/li[2]//button[1][1]"
manage_profile_physicallocation_toggle_yes                          = "//span[contains(text(),'yes')]"
manage_profile_serviceareas_title                                   = "//h5[contains(text(),'Service areas')]"
manage_profile_serviceareas_edit_link                               = "xpath=//section[@class='zk9a6o-0 jEaRPI']/ul/li[3]//button[1][1]"
manage_profile_servicearea_allNZ_option                             = "//label[@for='nz']"
manage_profile_servicearea_southisland_option                       = "//label[@for='south']"
manage_profile_edit_save_button2                                    = "//reach-portal//button[contains(text(),'Save')]"
manage_profile_phonenumber_title                                    = "//h5[contains(text(),'Phone Numbers')]"
manage_profile_phonenumber_edit_link                                = "(//section[@class='zk9a6o-0 jEaRPI']/ul/li[4]//button[1])[1]"
manage_profile_phonenumber_number_input                             = "//input[@placeholder='Number']"
manage_profile_emailaddress_title                                   = "//h5[contains(text(),'Email address')]"
manage_profile_emailaddress_edit_link                               = "(//section[@class='zk9a6o-0 jEaRPI']/ul/li[5]//button[1])[1]"
manage_profile_emailaddress_input                                   = "//input[@placeholder='Email']"
manage_profile_websiteurl_title                                     = "//h5[contains(text(),'Website URL')]"
manage_profile_websiteurl_edit_link                                 = "xpath=//section[@class='zk9a6o-0 jEaRPI']/ul/li[6]//button[1][1]"
manage_profile_websiteurl_input                                     = "//input[@placeholder='Website URL']"
manage_profile_saved_successfully_msg                               = "//div[contains(text(),'Saved successfully.')]"
manage_profile_edit_close_button                                    = "xpath=//img[contains(@alt,'close')]"
manage_profile_edit_window                                          = "//div[3]/div/div/div"
# -----------------------------------------------------------------------------
# Gallery Section
# -----------------------------------------------------------------------------
manage_profile_edityourgallery_title                                = "xpath=//h2[contains(text(),'Edit your gallery')]"
manage_profile_edityourgallery_withcrown_title                      = "xpath=//h2[contains(text(),'Edit your gallery')]//parent::section/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
manage_profile_image_add_button                                     = "xpath=//button[contains(text(),'ADD IMAGES')]"
manage_profile_video_add_button                                     = "xpath=//button[contains(text(),'ADD VIDEOS')]"
manage_profile_gallery_image_addbutton                              =  "(//reach-portal//div[@data-testid='UploadButtonsContainer']//button[1])[1]"
manage_profile_gallery_video_addbutton                              =  "(//reach-portal//div[@data-testid='UploadButtonsContainer']//button[1])[2]"
manage_profile_gallery_image_video_input                            = "//input[@accept='image/jpeg, image/png']"
manage_profile_gallery_video_input                                  = "//input[@placeholder='Video URL']"
manage_profile_gallery_edit_link                                    = "//h2[contains(text(),'Edit your gallery')]//parent::section//button"
manage_profile_gallery_first_item_remove                            = "(//img[@alt='Remove item'])[1]"
manage_profile_gallery_second_item_remove                           = "(//img[@alt='Remove item'])[2]"
# -----------------------------------------------------------------------------
# Manage Categories Section
# -----------------------------------------------------------------------------
manage_profile_manageyourcategories_title                           = "xpath=//h2[contains(text(),'Manage your categories')]"
manage_profile_categories_edit_link                                 = "xpath=(//h2[contains(text(),'Manage your categories')]//parent::section//div/button)[1]"
manage_profile_categories_remove_firstitem_selected                 = "//reach-portal//div[@class='sc-1hs2p4r-2 eicuDf']//button[@title='Remove']"
manage_profile_categories_dropdown                                  = "//div[@class='bwc68y-0 hIiVAH']/div[1]/div/div[2]/div"
manage_profile_categoryboost_dropdown                               = "//div[@class='gcn04e-0 kvcIGZ']/div[1]/div/div[2]/div"
manage_profile_category_beauty_therapy_select                       = "//div[@class=' css-11unzgr']/div[contains(text(),'Beauty Therapy')]"
manage_profile_category_plumbers_select                             = "//reach-portal//div[contains(text(),'Plumbers')]"
manage_profile_category_current_value                               = "//h2[contains(text(),'Manage your categories')]//parent::section//span[1]"
manage_profile_categoryboost_edit_link                              = "xpath=(//h2[contains(text(),'Manage your categories')]//parent::section//div/button)[2]"
manage_profile_categoryboost_beautytherapy_remove                   = "//span[contains(text(),'Beauty Therapy')]/button[@title='Remove']"
manage_profile_categoryboost_plumber_remove                         = "//span[contains(text(),'Plumbers')]/button[@title='Remove']"
# -----------------------------------------------------------------------------
# Main Information Section
# -----------------------------------------------------------------------------
manage_profile_edityourmaininfo_title                               = "xpath=//h2[contains(text(),'Edit your main info')]"
manage_profile_businesshours_title                                  = "xpath=//h5[contains(text(),'Business hours')]"
manage_profile_businesshours_edit_link                              = "xpath=//h5[contains(text(),'Business hours')]//parent::div/div/button"
manage_profile_monday_businesshours_value                           = "xpath=//div[@class=' css-1hwfws3']/div"
manage_profile_maininfo_dropdown                                    = "xpath=//div[contains(@class,'indicatorContainer')]"
manage_profile_businesshours_24hours                                = "//div[contains(text(),'24 Hours')]"
manage_profile_businesshours_closed                                 = "//div[@class=' css-11unzgr']/div[contains(text(),'Closed')]"
manage_profile_businessdescription_title                            = "xpath=//h5[contains(text(),'Business description')]"
manage_profile_businessdescription_edit_link                        = "xpath=//h5[contains(text(),'Business description')]//parent::div/div/button"
manage_profile_businessdescription_input                            = "xpath=//textarea[@placeholder='Business description']"
manage_profile_keywords_title                                       = "xpath=//h5[contains(text(),'Keywords')]"
manage_profile_keywords_edit_link                                   = "xpath=//h5[contains(text(),'Keywords')]//parent::div/div/button"
manage_profile_maininfo_keywords_select                             = "//reach-portal/div[3]/div/div/div/div/div/div/div[1]/div/div/div[1]/div[1]"
manage_profile_keywords_dropdown_firstoption                        = "xpath=//div[@class=' css-11unzgr']/div"
manage_profile_keywords_remove_button                               = "xpath=//div[@class='css-i0y2du']//button"
manage_profile_keywords_fisrtoption_selected                        = "//ul/li[2]/div[2]/span[1]"
manage_profile_keywords_secondoption_selected                       = "//ul/li[2]/div[2]/span[2]"
manage_profile_paymentoption_title                                  = "xpath=//h5[contains(text(),'Payment Options')]"
manage_profile_paymentoption_withcrown_title                        = "xpath=//h5[contains(text(),'Payment Options')]/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
manage_profile_paymentoption_edit_link                              = "xpath=//h5[contains(text(),'Payment Options')]/parent::div/div/button[contains(text(),'Edit')]"
manage_profile_paymentoption_remove_secondoption                    = "//div[@class='bwc68y-0 hIiVAH']/span[2]/button"
manage_profile_paymentoptions_dd                                    = "//div[@class=' css-11unzgr']/div[contains(text(),'Direct Debit')]"
manage_profile_bannerimage_title                                    = "xpath=//h5[contains(text(),'Banner Image')]"
manage_profile_bannerimage_withcrown_title                          = "//h5[contains(text(),'Banner Image')]/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
manage_profile_bannerimage_edit_link                                = "//h5[contains(text(),'Banner Image')]//parent::div//button"
manage_profile_banner_add_image_link                                = "(//p[contains(text(),'Upload your banner image here.')]//parent::div//button)[1]"
manage_profile_banner_input                                         = "//input[@accept='image/jpeg, image/png']"
manage_profile_banner_img_remove                                    = "//img[@alt='Remove item']"
manage_profile_whatmakesusdiff_title                                = "//h5[contains(text(),'What makes us different')]"
manage_profile_whatmakesusdiff_withcrown_title                      = "//h5[contains(text(),'What makes us different')]/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
manage_profile_whatmakesusdiff_edit_link                            = "//h5[contains(text(),'What makes us different')]//parent::div//button"
manage_profile_whatmakesusdiff_input                                = "xpath=//textarea[@placeholder='What makes your business different...']"
# -----------------------------------------------------------------------------
# View Profile Section
# -----------------------------------------------------------------------------
manage_profile_viewyourprofile_title                                = "xpath=//h2[contains(text(),'Your profile is live on Yellow')]"
manage_profile_viewyourprofile_button                               = "xpath=//a[contains(text(),'View your profile')]"
# -----------------------------------------------------------------------------
# Additional Information Section
# -----------------------------------------------------------------------------
manage_profile_edityouradditionalinfo_title                        = "xpath=//h2[contains(text(),'Edit your additional info')]"
manage_profile_teammembers_title                                   = "xpath=//h5[contains(text(),'Team Members')]"
manage_profile_teammembers_withcrown_title                         = "xpath=//h5[contains(text(),'Team Members')]/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
manage_profile_teammembers_edit_link                               = "xpath=(//section[@class='zk9a6o-0 jEaRPI']/ul/li[1]//button[1])[2]"
manage_profile_teammember1_edit_link                               = "xpath=//div[@class='css-1lx7oj']/div[1]//button[contains(text(),'Edit')]"
manage_profile_teammember1_lastname_input                          = "//input[@placeholder='Last Name']"
manage_profile_parking_title                                       = "xpath=//h5[contains(text(),'Parking')]"
manage_profile_parking_edit_link                                   = "xpath=//h5[contains(text(),'Parking')]//parent::div/div/button"
manage_profile_parking_dropdown                                    = "//div[@class='bwc68y-0 hIiVAH']/div[1]/div/div[2]/div"
manage_profile_parking_free_Offstreet                              = "//reach-portal//div[contains(text(),'Free Off-Street')]"    #//div[@class='css-2613qy-menu']
manage_profile_parking_free_Offstreet_remove                       = "//span[contains(text(),'Free Off-Street')]//button[@title='Remove']"
manage_profile_freewifi_title                                      = "xpath=//h5[contains(text(),'Free wifi available')]"
manage_profile_freewifi_withcrown_title                            = "xpath=//h5[contains(text(),'Free wifi available')]/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
#manage_profile_freewifi_radio_button                               = "xpath=(//section[@class='zk9a6o-0 jEaRPI']/ul/li[2]//button[1])[2]"
manage_profile_freewifi_radio_button                               = "xpath=//button[contains(@aria-label,'hasWifi')]"
manage_profile_socialmedia_title                                   = "xpath=//h5[contains(text(),'Social media links')]"
manage_profile_socialmedia_withcrown_title                         = "//h5[contains(text(),'Social media links')]/div[@data-for='premiumCrown']/img[@alt='Premium Only']"
manage_profile_socialmedia_edit_link                               = "xpath=(//section[@class='zk9a6o-0 jEaRPI']/ul/li[5]//button[1])[2]"
manage_profile_socialmedia_youtube_input                           = "//input[@placeholder='YouTube Url']"
manage_profile_yearestablished_title                               = "xpath=//h5[contains(text(),'Year established')]"
manage_profile_yearestablished_edit_link                           = "xpath=//h5[contains(text(),'Year established')]//parent::div/div/button"
manage_profile_yearestablished_input                               = "//input[@placeholder='Year Established']"

#--------------------------------------------------------------------------------
#Remove your listing
#--------------------------------------------------------------------------------
manage_profile_removeyourlisting_title                             = "//h2[contains(text(),'Remove your listing')]"
manage_profile_removeyourlisting_submit_req_button                 = "//button[contains(text(),'SUBMIT REQUEST')]"
manage_profile_removeyourlisting_reason_placeholder                = "//div[contains(text(),'Please choose a removal reason...')]"
manage_profile_removeyourlisting_reason_dropdown                   = "//div[@class=' css-2b097c-container']//div[@class=' css-tlfecz-indicatorContainer']"
manage_profile_removeyourlisting_reason_firstoption                = "//div[contains(text(),'subscription anymore')]"
manage_profile_removeyourlisting_reason_secondoption               = "//div[contains(text(),'unhappy')]"
manage_profile_removeyourlisting_reason_thirdoption                = "//div[contains(text(),'permanently closing')]"
manage_profile_removeyourlisting_reason_fourthoption               = "//div[contains(text(),'Other reason')]"
manage_profile_removeyourlisting_req_removal_button                = "//button[contains(text(),'Request Removal')]"
manage_profile_removeyourlisting_submit_req_msg_holder             = "//h2[contains(text(),'Remove your listing')]//parent::div//p"
manage_profile_removeyourlisting_submit_req_msg_close_button       = "//button[contains(text(),'Close')]"
# -----------------------------------------------------------------------------
# DLP
# -----------------------------------------------------------------------------
dlp_business_logo                                                  = "//div[@class='logo d-flex align-items-center']"
dlp_Trading_name                                                   = "//h1[@class='title']"
dlp_Legal_Tradingname                                              = "//p[contains(text(),'Also known as:')]"
dlp_servicing_area                                                 = "//span[@itemprop='areaServed']"
dlp_phonenumber                                                    = "//div[contains(text(),'Phone')]"
dlp_phonenumber_primary                                            = "//a[@data-ga-id='Phone_Number_Click_Primary']/span"
dlp_email_address                                                  = "//div[contains(text(),'Email')]"
dlp_emailaddress_value                                             = "//div[@class='dlp-own-links']/div/div[4]/meta[contains(@content,'${manage_profile_updated_email_address}')]"
dlp_website                                                        = "//div[contains(text(),'Website')]"
dlp_websiteurl_value                                               = "(//a[@data-ga-id='Website_Link'])[1]"
dlp_additionalinfo_tab                                             = "//a[@id='additional-info-tab']"
dlp_officemember_title                                             = "//h2[contains(text(),'Office Team')]"
dlp_officemember1_value                                            = "//*[@id='additionalInfo']//div[@class='component-container team-members-container']//h6/p"
dlp_WiFi_title                                                     = "//h2[contains(text(),'Wi-Fi')]"
dlp_WiFi_Available                                                 = "//div[@class='component-container free-wifi-container']/p"
dlp_parkingoptions_title                                           = "//h2[contains(text(),'Parking options')]"
dlp_parkingoption_value                                            = "//span[@class='parking-option']"
dlp_yearestablished                                                = "//h2[contains(text(),'Year est.')]"
dlp_yearestablished_value                                          = "//div[@class='component-container year-established-container']//p"
dlp_follow_us                                                      = "//h2[contains(text(),'Follow Us')]"
dlp_follow_us_value                                                = "//div[@class='component-container follow-us-container']/div/a[1]"
dlp_listedin_title                                                 = "(//h6[@class='listed-in-title'])[2]"
dlp_listedin_value                                                 = "(//div[@class='listed-in-categories'])[2]//a"
dlp_opening_hours_title                                            = "//h2[contains(text(),'Opening hours')]"
dlp_openinghours_monday_value                                      = "(//div[contains(@class,'opening-hours-times')])[1]/time"
dlp_productandservices_title                                       = "//h2[contains(text(),'Products and Services')]"
dlp_productandservices_value                                       = "//div[@class='component-container keywords-container']/p"
dlp_businessdesc_title                                             = "//h2[contains(text(),'About')]"
dlp_businessdesc_value                                             = "//div[@class='about-container component-container']/div/p"
dlp_paymentoptions_title                                           = "//h2[contains(text(),'Payment options')]"
dlp_paymentoptions_DD                                              = "//span[contains(text(),'Direct Debit')]"
dlp_street_address                                                 = "//span[@itemprop='streetAddress']"
dlp_whatmakesusdiff_title                                          = "//h2[contains(text(),'What makes us different')]"
dlp_whatmakesusdiff_text                                           = "//h2[contains(text(),'What makes us different')]//parent::div/div/p"
dlp_gallery_image                                                  = "//div[@class='dlp-images-container']/div[1]/img"
dlp_gallery_video                                                  = "//div[@class='dlp-images-container']/div[2]/img"
dlp_main_tab                                                       = "//a[contains(text(),'Main')]"
dlp_banner_image                                                   = "(//h2[contains(text(),'What makes us different')]//parent::div/following::div)[1]"

##--------------------------------------------------------------------------------------------------------
#View profile completion status
##--------------------------------------------------------------------------------------------------------
manage_profile_profile_completion_status                           = "//h2[contains(text(),'Complete your profile')]"
manage_profile_profile_completion_percentage                       = "//h2[contains(text(),'Complete your profile')]//parent::div//parent::div/div[2]/section//*[name()='svg']//*[name()='text']"
manage_profile_add_link                                            = "//h2[contains(text(),'Complete your profile')]//parent::div//parent::div//following-sibling::ul/li[1]/button"
manage_profile_gopremium_button                                    = "//button[contains(text(),'Go Premium')]"
manage_profile_LHS                                                 = "(//a[contains(text(),'Manage Profile')])[2]"