# -----------------------------------------------------------------------------
# Staff Assistance Flow
# -----------------------------------------------------------------------------
staff_assistance_customer_email_inputtext                       = "xpath=//*[@id='emailInput']"
staff_assistance_company_input                                  = "//*[@id='customerInput']"
staff_assistance_company_dropdown                               = "xpath=//*[@id='customerInput']/div/div[2]/div"
staff_assistance_company_select_button                          = "xpath=//button[contains(text(),'Done')]"
staff_assistance_company_dropdown_option_01                     = "xpath=//div[contains(@class,' css-1n7v3ny-option')]"
staff_assistance_changed_company_dropdown_option_01             = "xpath=//div[contains(@class,' css-yt9ioa-option')]"
staff_assistance_changed_company_dropdown_option_02             = "xpath=//div[contains(@class,' css-1n7v3ny-option')]"
staff_assistance_header_banner_change_link                      = "xpath=//a[contains(text(),'Change')]"
staff_assistance_email_address_label                            = "xpath=//*[contains(@data-testid,'currentAccountEmail')]"
staff_assistance_currently_access_label                         = "xpath=//*[@id='gatsby-focus-wrapper']/div[4]/div/div/span"
staff_assistance_company_email_label                            = "xpath=//*[contains(@data-testid,'companyEmail')]"
staff_assistance_company_name_label                             = "xpath=//*[contains(@data-testid,'companyName')]"
staff_assistance_header_text_label                              = "You are currently acting on behalf of"
staff_assistance_customer_email_address_01                      = "kumindu777+yellowms@gmail.com"
staff_assistance_header_company_name_label_0101                 = "Yellow NZ Advertising MS"
staff_assistance_customer_email_address_02                      = "kumindu777+yellowsa@gmail.com"
staff_assistance_header_company_name_label_0201                 = "Test Business Search Ads Go Live"
staff_assistance_header_company_link                            = "xpath=//a[contains(@href, '/my-yellow/choose-customer')]"
staff_assistance_customer_email_address_03                      = "kumindu777+fingoo@gmail.com"
staff_assistance_header_company_name_label_0301                 = "Ian Charle Langdon"
staff_assistance_header_company_name_label_0302                 = "Sriwis Foods"
staff_assistance_select_button                                  = "//a[contains(text(),'Select')]"
