#-----------------------------------------------------------------------------------------------------------------------
# Search ads
#-----------------------------------------------------------------------------------------------------------------------
searchads_profile_link                  ="/our-products/search-ads/"
get_started_button_first                ="xpath=//*[@id='hero:-google-search-ads']/div[1]/div[2]/a"
how_does_it_cost                        ="xpath=//*[@id='google-search-ads-buy-journey']/div[1]/span"
adjut_your_budget_video                 ="xpath=//*[@id='google-search-ads-buy-journey']/div[2]/video"
get_started_button_second               ="xpath=//button[contains(text(), 'Get Started')]"
my_full_name_textbox                    ="xpath=//*[@id='My full name is']"
search_ad_onboarding_url                ="/our-products/search-ads/onboarding/1"
business_email_textbox                  ="xpath=//*[@id='My business email']"
consent_checkbox                        ="xpath=//input[contains(@type,'checkbox')]"
next_button                             ="xpath=//button[contains(text(),'Next')]"
my_business_category_header             ="xpath=//h2[contains(text(),'My business categories')]"
business_categories_dropdown            ="xpath=//div[contains(@class,'indicatorContainer')]"
select_business_category                ="xpath=//*[@id='react-select-2-option-0']"
next_business_category                  ="xpath=//button[contains(text(), 'Next')]"
select_business_address_dropdown        ="xpath=//*[@id='GooglePlacesAutocomplete']"
unit_no_textbox                         ="xpath=//*[@id='subpremise']"
floor_no_textbox                        ="xpath=//*[@id='floor']"
building_textbox                        ="xpath=//*[@id='premise']"
in_these_regions_tab                    ="xpath=//*[@id='regions']"
select_region_dropdown                  ="xpath=//*[@id='react-select-3-option-3']"
recommended_budget                      ="xpath=//*[@id='gatsby-focus-wrapper']/div/section/div[1]/h1"
target_region_tooltip                   ="xpath=//*[@id='gatsby-focus-wrapper']/div/div/section/div[2]/div[2]/form/div/div[2]/div/div[1]"
select_budget_slider                    ="xpath=//div[@role='slider']"
phone_number_textbox                    ="xpath=//*[@id='number']"
book_callback_button                    ="xpath=//button[contains(text(), 'Book Callback')]"
budget_value_selected                   ="xpath=//p[contains(.,'00')]"
thank_you_msg                           ="xpath=//h1[contains(text(),'Thank you')]"
near_by_business_tab                    ="xpath=//*[@id='proximity']"
radius_tootip                           ="xpath=//div[contains(@class,'rc-slider-tooltip-inner')]"
book_call_popup_header                  ="xpath=//h2[contains(text(),'the best time to get in touch?')]"
later_book_call_radio_button            ="xpath=//div[@role='listbox']/img[@alt='unchecked']"
now_book_call_radio_button              ="xpath=//div[@role='listbox']/img[@alt='checked']"
select_best_time_dropdown               ="xpath=//*[@id='timeslot']"
select_best_days_monday_checkbox        ="xpath=//*[@id='Monday']"
select_morning_time_menu_item           ="xpath=//div[contains(@id,'-option-0')]"
second_book_callback_button             ="xpath=//div[contains(@class,'sc-6j03um-2')]/button[contains(text(), 'Book Callback')]"
phone_number_error_message              ="xpath=//p[contains(text(),'Please enter a valid phone number.')]"
error_msg_text_phone_no                 ="Please enter a valid phone number."
preferred_time_error_msg                ="xpath=//p[2][contains(text(),'Please choose a preferred time and at least one preferred day.')]"
error_msg_preferred_time_day            ="Please choose a preferred time and at least one preferred day."
views_per_month_value                   ="xpath=//div[1][contains(@class,'bgerkg')]/strong"
leads_per_month_value                   ="xpath=//div[2][contains(@class,'bgerkg')]/strong"
impressions_per_month_value             ="xpath=//div[3][contains(@class,'bgerkg')]/strong"
link_to_your_website                    ="xpath=//*[@id='url']"
recommended_price_from_dropdown         ="xpath=//*[@id='price']/div/div[1]/div"
sa_add_to_cart_button                   ="xpath=//button[contains(text(), 'Add to cart')]"
sa_checkout_button                      ="xpath=//a[contains(text(), 'Checkout')]"