# ----------------------------------------------------------------------------------------------------------------------
# Axle - Web Elements Locators
# ----------------------------------------------------------------------------------------------------------------------
axle_login_link                                     = "xpath=//*[@id='page.sidebar.login']/a"
axle_login_popup_focus                              = "css=#loginform"
axle_login_username_textfield                       = "css=#login-username-tid"
axle_login_password_textfield                       = "css=#login-password-tid"
axle_login_popup_submit_button                      = "css=#submitLogin"
axle_side_menu_customers                            = "css=#menu-tid-customers"
axle_side_menu_customers_click                      = "xpath=//*[@id='mainNav']/ul/li[6]/a"
axle_customer_search_account_number_textfield       = "css=#id_filter_accountNumber"
axle_customer_search_account_name_textfield         = "css=#id_filter_accountName"
axle_customer_search_eplus_id_textfield             = "css=#id_filter_eplusId"
axle_customer_search_apply_button                   = "css=#filter-apply-btn-tid"
axle_search_results_account_number                  = "css=#customersTable > tbody > tr:nth-child(1) > td:nth-child(1)"
axle_search_results_account_name                    = "css=#customersTable > tbody > tr:nth-child(1) > td:nth-child(2)"
axle_search_results_eplus_id                        = "css=#customersTable > tbody > tr:nth-child(1) > td:nth-child(3)"
axle_search_results_view                            = "css=#customersTable > tbody > tr:nth-child(1) > td:nth-child(5) > a:nth-child(1)"
axle_search_results_message                         = "xpath=//*[@id='page.document.results_view']/div"
axle_main_menu                                      = "css=#mainNav"
axle_sign_in_page_title                             = "Yellow | Product Catalogue"
no_results_label                                    = "No customers found."
axle_loadingpage_block                              = "xpath=//div[@id='loadingPage'][contains(@style,'display: block;')]"
axle_loadingpage_none                               = "xpath=//div[@id='loadingPage'][contains(@style,'display: none;')]"
axle_results_customer_view_button                   = "xpath=//a[contains(@data-name,'view-customer')]"
axle_customer_search_account_name_dropdown          = "xpath=//*[@id='s2id_id_filter__filter.accountName']/a/span[2]/b"
axle_account_name_dropdown_equals_option            = "xpath=//*[@id='select2-drop']/ul/li[2]/div"
